//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int Product { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Price Price { get; set; }
    }
}
